version: 2.1

parameters:
  cimg-base-tag:
    type: string
    default: "v0.4.2" 

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

aliases:
  - &notify_slack_on_fail
    slack/notify:
      channel: 'C056RL4BXG9' #status-go channel
      event: fail
      template: basic_fail_1

jobs:
  build:
    parameters:
      push_release:
        type: boolean
        default: false
    machine:
      image: default
    environment:
      CIMGBASETAG: << pipeline.parameters.cimg-base-tag >>
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: curl --silent -L --output ~/regctl https://github.com/regclient/regclient/releases/download/v0.3.9/regctl-linux-amd64
      - run: chmod a+x ~/regctl
      - run: docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run: docker buildx version
      - run: docker context create cictx
      - run: docker buildx create cictx --platform linux/amd64,linux/arm64 --use
      - run: docker buildx ls
      - run: echo "$DOCKER_REGISTRY_PASSWORD" | base64 -d | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin "$DOCKER_REGISTRY_HOST"
      - run: ./build-images.sh
      - when:
          condition: <<parameters.push_release>>
          steps:
            - deploy:
                name: Push docker image
                command: |
                  ./build-images.sh latest
      - slack/notify:
          event: fail
          template: basic_fail_1
  check_version:
    executor: machine-executor
    steps:
        - checkout
        - run: make check-updates
        - *notify_slack_on_fail


orbs:
  slack: circleci/slack@4.1

workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build:
          context: arangodboasis
          filters:
            tags:
              ignore: /.*/
      - build:
          context: arangodboasis
          push_release: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - check_version:
          context:
            - arangodboasis


  # Monthly check for new versions of cimg-go
  monthly_new_version_check:
    jobs:
      - check_version:
          context:
            - arangodboasis
    triggers:
      - schedule:
          # Midnight UTC on the 1st of every month
          cron: 0 0 1 * *
          filters:
            branches:
              only: master
    